---
- name: Install required packages
  package:
    name:
      - docker.io
      - python3-pip
    state: latest

# Docker compose is too old on Ubuntu 18.04, and there is no
# PPA (for project political reasons) so we have to curl it...
- name: Download latest docker-compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version}}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: +x

- name: Install python SDKs
  pip:
    name:
      - docker
      - docker-compose
      - setuptools
    state: latest

- name: Create working dir
  file:
    state: directory
    path: /opt/nginx

- name: Copy across certificate files
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/private/{{ item }}"
  with_items:
    - fullchain.pem
    - privkey.pem
  when: host_ssl_termination == true

- name: Configure nginx reverse proxy templates
  template:
    src: "{{ item }}.j2"
    dest: "/opt/nginx/{{ item }}"
  with_items:
    - docker-compose.yml
    - nginx.conf

- name: Configure nginx reverse proxy templates
  template:
    src: "{{ item }}.j2"
    dest: "/opt/nginx/{{ item }}"
  with_items:
    - ssl.conf
  when: host_ssl_termination == true

- name: Copy in config for registry
  copy: src=cache-config.yml dest=/opt/nginx/cache-config.yml

- name: Get DH-Curve
  # This is safe to do, as having a DH curve does not help you
  # find the randomly selected point, as a by-product of forward secrecy
  get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /etc/ssl/private/ffdhe2048.txt
  when: host_ssl_termination == true

- name: Set local machine to use configured mirror
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Restart docker service
  service:
    name: docker
    state: restarted

- name: Run frontend service
  docker_compose:
    project_src: /opt/nginx
